// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfZKMYUl9fgFl0IGj7XfkPMe94QL5gTR4',
    appId: '1:235621629856:web:dae0e1cb48c8f09f04eec5',
    messagingSenderId: '235621629856',
    projectId: 'fitness-app-307df',
    authDomain: 'fitness-app-307df.firebaseapp.com',
    storageBucket: 'fitness-app-307df.firebasestorage.app',
    measurementId: 'G-9YS61W96EQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC9jhlGO9xFLWHwWUWjYnJv93t6T8B6G4',
    appId: '1:235621629856:android:cfa525737e98bde004eec5',
    messagingSenderId: '235621629856',
    projectId: 'fitness-app-307df',
    storageBucket: 'fitness-app-307df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ8LeDSvSh8Fh2SxRIAezJ5Cok9Y7Otug',
    appId: '1:235621629856:ios:a54dccfcee17806504eec5',
    messagingSenderId: '235621629856',
    projectId: 'fitness-app-307df',
    storageBucket: 'fitness-app-307df.firebasestorage.app',
    iosBundleId: 'com.example.fitnessapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ8LeDSvSh8Fh2SxRIAezJ5Cok9Y7Otug',
    appId: '1:235621629856:ios:a54dccfcee17806504eec5',
    messagingSenderId: '235621629856',
    projectId: 'fitness-app-307df',
    storageBucket: 'fitness-app-307df.firebasestorage.app',
    iosBundleId: 'com.example.fitnessapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfZKMYUl9fgFl0IGj7XfkPMe94QL5gTR4',
    appId: '1:235621629856:web:e958e5021bd752bb04eec5',
    messagingSenderId: '235621629856',
    projectId: 'fitness-app-307df',
    authDomain: 'fitness-app-307df.firebaseapp.com',
    storageBucket: 'fitness-app-307df.firebasestorage.app',
    measurementId: 'G-B2ZFGCR95C',
  );
}
